[build]
  functions = "functions/"
[[headers]]
  for = "/*"
  [headers.values]
  	cache-control = '''
	    max-age=0,
      no-cache,
      no-store,
      must-revalidate'''
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src data: 'unsafe-inline'  https:; script-src data: 'unsafe-inline'  https: blob:; style-src data: 'unsafe-inline' https:; img-src data: https: blob:; font-src data: https:; connect-src https: wss: blob:; media-src https: blob:; object-src https:; child-src https: data: blob:; form-action https:; block-all-mixed-content"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy= "geolocation=(), microphone=()"
    X-Robots-Tag="noindex"